# Generated by Django 5.2.8 on 2025-12-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='patient', max_length=20),
        ),
    ]
