# Generated by Django 5.2.8 on 2025-12-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_Appointment', '0004_medicalnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalnotes',
            name='appointment',
        ),
    ]
