# Generated by Django 5.2.8 on 2025-12-06 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_Appointment', '0006_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('experiance', models.IntegerField()),
                ('qualification', models.CharField()),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Doctor_Appointment.userprofile')),
            ],
        ),
    ]
