# Generated by Django 5.2.8 on 2025-12-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_Appointment', '0007_doctor_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_details',
            old_name='experiance',
            new_name='experience',
        ),
    ]
