# Generated by Django 5.2.8 on 2025-12-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_Appointment', '0009_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
