# Generated by Django 5.2.8 on 2025-12-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_Appointment', '0010_alter_appointment_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
